<!DOCTYPE html>
<html>
<head>
    <title>$title$</title>
    <link rel="stylesheet" type="text/css" href="my.css"/>
    <div class="navbar-header" style="padding-top : 30px;">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!-- <a class="navbar-brand" href="#"</a> | <a href="http://cloud.toast.com">TOASTCloud</a> --->
        </div>

</head>

<body>
